export const Types = {
  GET_ALL_ELECTIONS: 'GET_ALL_ELECTIONS',
  NEW_ELECTION: 'NEW_ELECTION',
  SET_ELECTION_DATA: 'SET_ELECTION_DATA',
  GET_ELECTION_FOR_STAT: 'GET_ELECTION_FOR_STAT',
  DELETE_ELECTION: 'DELETE_ELECTION',
  GET_PORTFOLIOS: 'GET_PORTFOLIOS',
  ADD_PORTFOLIOS: 'ADD_PORTFOLIOS',
  REMOVE_PORTFOLIO: 'REMOVE_PORTFOLIO',
}
